name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_DEFAULT_HOST_TRIPLET: x64-windows
    strategy:
      matrix:
        include:
          - qt_ver: 6.8.1
            qt_arch: win64_msvc2022_64
            msvc_arch: x64
            version: 2022
            qt_arch_install: msvc2022_64
            build_type: Debug

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: ${{ matrix.msvc_arch }}
      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "C:/vcpkg"
          runVcpkgInstall: true
          vcpkgJsonGlob: "cmake/vcpkg.json"
          vcpkgConfigurationJsonGlob: "cmake/vcpkg-configuration.json"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U tmate
      - name: SSH connection to Actions
        run: |
            python -m tmate
